#!/usr/bin/env python3
#Import Library
import socket

#script Name: Ops401challenge44
#Author: Bubacarr Darboe
#Date: 12/07/2020
#Description of purpose: pentest 1
#Declaration of variable

#Main

sockmod = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
timeout = 2000 #timeout value.
sockmod.settimeout(timeout)

hostip = input("Enter IP address: ")
portno = int(input("Enter your port number: "))

def portScanner(portno):
    if sockmod.bind((hostip, portno)): #a bind socket function call
        print("Port closed")
    else:
        print("Port open")

portScanner(port)
