#!/usr/bin/env python
#Import Library
import socket

#script Name: Ops401challenge44
#Author: Bubacarr Darboe
#Date: 12/07/2020
#Description of purpose: pentest 1
#Declaration of variable

#Main

sockmod = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
timeout = # TODO: Set a timeout value here.
sockmod.settimeout(timeout)

hostip = # TODO: Collect a host IP from the user.
portno = # TODO: Collect a port number from the user, then convert it to an integer data type.

def portScanner(portno):
    if sockmod.FUNCTION((hostip, portno)): # TODO: Replace "FUNCTION" with the appropriate socket.function call as found in the [socket docs](https://docs.python.org/3/library/socket.html)
        print("Port closed")
    else:
        print("Port open")

portScanner(port)
