#!/usr/bin/env python
###Import Library###
import os, time
import subprocess
import requests


###script Name: Ops401challenge37###
###Author: Bubacarr Darboe###
###Date: 11/24/2020###
###Description of purpose: Cookies###
###Declaration of variable###

# targetsite = input("Enter target site:") # Uncomment this to accept user input target site
targetsite = "http://www.whatarecookies.com/cookietest.asp" # Comment this out if you're using the line above
response = requests.get(targetsite)
cookie = response.cookies

#Declaration of functions
def bringforthcookiemonster(): # Because why not!
    print('''

              .---. .---.
             :     : o   :    me want cookie!
         _..-:   o :     :-.._    /
     .-''  '  `---' `---' "   ``-.
   .'   "   '  "  .    "  . '  "  `.
  :   '.---.,,.,...,.,.,.,..---.  ' ;
  `. " `.                     .' " .'
   `.  '`.                   .' ' .'
    `.    `-._           _.-' "  .'  .----.
      `. "    '"--...--"'  . ' .'  .'  o   `.

        ''')

bringforthcookiemonster()
print("Target site is " + targetsite)
print(cookie)

htmlrequest = requests.get(targetsite, cookies=cookie)
website = cookiemonsterhtml.text

with open ('cookiemonster.html', 'w') as file:file.write(website)
# Print to screen that website is opening
print("site opening...")
# Open it with Firefox
os.system("firefox /home/bdabo/cookiemonster.html")
exit()
#End
