#!/usr/bin/env python
###Import Library###
import os

###script Name: Ops401challenge31###
###Author: Bubacarr Darboe###
###Date: 11/16/2020###
###Description of purpose: malware detection###

###Declaration of variable###
fileName = input("Enter file to search")
dirName = input("Enter directory containing file")

###Declaration of Functions###
###Main###

# Search each file in the directory by name
for file in os.listdir('C:\\users\bdabo\\'+ dirName):
    print(os.path.join(dirName, file))
# For each positive detection, print file name and location.
print(fileName, dirName)
# Print how many files were searched and how many hits were found
