#!/usr/bin/env python
#Import Library
import logging
import logging.handlers
import os
#script Name: Ops401challenge26
#Author: Bubacarr Darboe
#Date: 11/09/2020
#Description of purpose: logging errors
#Declaration of variable

#Main

handler = logging.handlers.WatchedFileHandler(
    os.environ.get("LOGFILE", "/var/log/yourapp.log"))
formatter = logging.Formatter(logging.BASIC_FORMAT)
handler.setFormatter(formatter)
root = logging.getLogger()
root.setLevel(os.environ.get("LOGLEVEL", "INFO"))
root.addHandler(handler)
 
try:
    exit(main())
except Exception:
    logging.exception("Exception in main()")
    exit(1)
    
  #End
