#!/usr/bin/python3
#Import Library
import socket

#script Name: Ops401challenge44
#Author: Bubacarr Darboe
#Date: 12/08/2020
#Description of purpose: banner grabbing
#Declaration of variable

#Main

def bannergrab(host, port):
    timeout = 3000
    sockmod = socket.socket()
    sockmod.bind
    sockmod.settimeout(timeout)
    print(sockmod.recv(1024))

def main():
    hostip = input("Enter IP address: ")
portno = int(input("Enter your port number: "))
    bannergrab(host, port)

main()
